[tool.poetry]
name = "crawler-clouds"
version = "0.1.0"
description = ""
authors = ["Alexandre Tomy <ale.tomy1996@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
